### ISSUE TITLE
Switch Pinout

### ISSUE THREAD

**Issue by MarkusPlehn** [tebl/c64-blinkendiag#3]
Hi, thanx for this Projekt.
I struggle with the 6pin Switches. Could you please specify the pinout of the correct Switch? Is the middle Pin the COM and it Switches to left and right? So Pin 2 is the middle, Pin 1 left and Pin 3 right?

**Comment by tebl** [comment]
It should be one with a black base like in this picture:
https://raw.githubusercontent.com/tebl/c64-blinkendiag/main/gallery/build_003.jpg

On the underside there's a square hole further towards one side, this
should be towards the top of the board. The article linked below should go
into further detail, if you should need it.

https://www.hackster.io/UtkarshVerma/6-pin-push-switch-working-7bb5ef

fre. 7. mai 2021, 17:08 skrev Markus_64 ***@***.***>:
